---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: {{.Release.Namespace}}
spec:  
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
        name: example
    spec:
      containers:
        - image: 'httpd:2.4'
          imagePullPolicy: IfNotPresent
          name: example
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              host:
              scheme: HTTP
              path: /
              httpHeaders:
              - name: Host
                value: {{.Values.hostname}}
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

