---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: {{.Release.Namespace}}
  labels:
    app: example
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
