---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: PV_NAME
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: PVC_NAME
    namespace: NAMESPACE
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    nodePublishSecretRef:
      name: longhorn-crypto-global
      namespace: longhorn-system
    nodeStageSecretRef:
      name: longhorn-crypto-global
      namespace: longhorn-system
    volumeAttributes:
      diskSelector: ""
      encrypted: "true"
      nodeSelector: ""
      numberOfReplicas: "2"
      staleReplicaTimeout: "20"
    volumeHandle: LONGHORN_VOL
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
status:
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: PVC_NAME
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: PV_NAME