---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <email_here>
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - '<hosted_zone_name>'
      dns01:
        route53:
          region: '<hosted_zone_region>'
          accessKeyID: '<access_key>'
          secretAccessKeySecretRef:
            name: aws-secret
            key: aws_secret_access_key
